### ISSUE TITLE
AttributeError: module 'attr' has no attribute 'frozen'

### ISSUE THREAD

**Issue by udit01** [Pasanlaksitha/Shazam-Downloader#2]
After installing , the requirements, latest versions, i'm getting the error:

```
$ python3 shazam_music_downloader.py
Traceback (most recent call last):
  File "shazam_music_downloader.py", line 4, in <module>
    from youtubesearchpython import VideosSearch
  File "/home/udit/.local/lib/python3.8/site-packages/youtubesearchpython/__init__.py", line 1, in <module>
    from youtubesearchpython.search import Search, VideosSearch, ChannelsSearch, PlaylistsSearch, CustomSearch, ChannelSearch
  File "/home/udit/.local/lib/python3.8/site-packages/youtubesearchpython/search.py", line 1, in <module>
    from youtubesearchpython.core.constants import *
  File "/home/udit/.local/lib/python3.8/site-packages/youtubesearchpython/core/__init__.py", line 1, in <module>
    from .video import VideoCore
  File "/home/udit/.local/lib/python3.8/site-packages/youtubesearchpython/core/video.py", line 7, in <module>
    from youtubesearchpython.core.requests import RequestCore
  File "/home/udit/.local/lib/python3.8/site-packages/youtubesearchpython/core/requests.py", line 1, in <module>
    import httpx
  File "/home/udit/.local/lib/python3.8/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/home/udit/.local/lib/python3.8/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/home/udit/.local/lib/python3.8/site-packages/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/home/udit/.local/lib/python3.8/site-packages/httpx/_transports/default.py", line 30, in <module>
    import httpcore
  File "/home/udit/.local/lib/python3.8/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/home/udit/.local/lib/python3.8/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/home/udit/.local/lib/python3.8/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/home/udit/.local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 10, in <module>
    from .._synchronization import Lock
  File "/home/udit/.local/lib/python3.8/site-packages/httpcore/_synchronization.py", line 13, in <module>
    import trio
  File "/home/udit/.local/lib/python3.8/site-packages/trio/__init__.py", line 76, in <module>
    from ._dtls import DTLSEndpoint, DTLSChannel
  File "/home/udit/.local/lib/python3.8/site-packages/trio/_dtls.py", line 136, in <module>
    @attr.frozen
AttributeError: module 'attr' has no attribute 'frozen'
```

**Comment by Pasanlaksitha** [comment]
install these requirements along with versions

youtube-dl==2021.12.17
youtube-search-python==1.6.6
yt-dlp==2023.3.4
